### ISSUE TITLE
Support for Webstorm 2024.2

### ISSUE THREAD

**Issue by Thebluedragon7** [KartanHQ/intellij-expo#183]
### Is your feature request related to a problem? Please describe.

Plugin is Incompatible with Webstorm 2024.2
`Incompatible: requires IDE build 241.* or earlier`

**Comment by andregreeff** [comment]
seeing the "stale" message above, I just checked this again now and it seems this plugin has been updated for the latest Jetbrains IDEs.

haven't tested any functionality yet, but it installs and load with no errors in WebStorm `2024.2.3`. the release notes for this project are utterly useless, seemingly a copy-paste of "Solve some minor issues and update dependencies" with each release. so going by the version alone, I _guess_ this was resolved with `1.2.2`?
